使用不許可APIチェックツールSpotbugs版の作成
nablarch/nablarch-unpublished-api-checker pull request #1
Opened 2021-11-24 05:16 UTC by kumagoro1202

2021-11-24 09:48 UTC, opengl-8080 requested changes

2021-11-24 09:48 UTC, opengl-8080 commented on pom.xml
> +    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
`project.build.sourceEncoding` は nablarch-parent で指定されているので不要では？

2021-11-24 09:48 UTC, opengl-8080 commented on src/test/java/nablarch/test/tool/findbugs/PublishedApisInfoTest.java
> +                        });
↓みたいにすると、より宣言的なコード※にできるかなと思いましたけどどうでしょう？（やりすぎ？）

※doFindBugs() 内の Stream 処理が「unpublishd api usage でフィルターして、start line でソートして、BugInstanceをフォーマットして、writerに書き出す」と読めるようになる。

```java
        private void doFindBugs(String outputFile, String classForCheck) throws IOException {
            ...
            try (final BufferedWriter writer = Files.newBufferedWriter(output)) {
                StreamSupport.stream(bugCollection.spliterator(), false)
                        .filter(this::isUnpublishedApiUsage)
                        .sorted(BY_START_LINE)
                        .map(this::formatBugInstance)
                        .forEach(writeTo(writer));
            }
        }

        private boolean isUnpublishedApiUsage(BugInstance bugInstance) {
            return "UPU_UNPUBLISHED_API_USAGE".equals(bugInstance.getType());
        }

        /** FindBugs版と出力順序が異なっていたためソースコード上の行番号でソート */
        private static final Comparator<BugInstance> BY_START_LINE = Comparator.comparing(bugInstance -> bugInstance.getAnnotations()
                .stream()
                .filter(it -> it instanceof SourceLineAnnotation)
                .map(it -> (SourceLineAnnotation) it)
                .map(SourceLineAnnotation::getStartLine)
                .findFirst()
                .orElse(0));

        private String formatBugInstance(BugInstance bugInstance) {
            StringBuilder sb = new StringBuilder();
            sb.append(bugInstance.getMessageWithPriorityTypeAbbreviation());
            sb.append("  ");
            sb.append(bugInstance.getAnnotationsForMessage(true).get(0));
            return sb.toString();
        }

        private Consumer<String> writeTo(BufferedWriter writer) {
            return formattedText -> {
                try {
                    writer.write(formattedText);
                    writer.newLine();
                } catch (IOException e) {
                    fail(e);
                }
            };
        }
```

**ポイント**

- `sorted()` に渡す Comparator は名前付けした定数(`BY_START_LINE`)で宣言して渡すことで、 `sorted by start line` と自然な英語で読めるように工夫
- 処理対象となる `BugInstance` の絞り込みをメソッド化して `filter` で独立して絞り込み
  - これによって、 `sorted()` の前に `filter` を持ってこれるようになる
- `BugInstance` を出力用のテキストにフォーマットする処理を `formatBugInstance()` に切り出して、 `map()` で成形するように修正
  - 1つ1つの関数をできるだけ小さくすることで、何をやっているかを読みやすくする目的
- Comparator.comparing() の引数に渡してる処理も Stream にしてるのは、こういう書き方もできるよね、という参考で（自分は気にならないけど、人によっては読みにくいと思うかも？）

2021-11-24 09:48 UTC, opengl-8080 commented on src/test/java/nablarch/test/tool/findbugs/PublishedApisInfoTest.java
> +            return sb.toString();
こっちのほうがスマートかも。

```java
return String.join("\r\n", Files.readAllLines(Paths.get(filePath), StandardCharsets.UTF_8));
```

ちなみに、ごっそりそのまま String で取り出したいなら、以下のようにもできます（改行コードは元のファイルのままになりますが）。

```java
return new String(Files.readAllBytes(Paths.get(filePath)), StandardCharsets.UTF_8);
```

今回は無理だけど、 Java 11 以上なら [Files.readString()](https://docs.oracle.com/javase/jp/11/docs/api/java.base/java/nio/file/Files.html#readString(java.nio.file.Path,java.nio.charset.Charset)) という選択肢も。

2021-11-24 09:48 UTC, opengl-8080 commented on src/test/java/nablarch/test/tool/findbugs/PublishedApisInfoTest.java
> +                                    writer.newLine();
`getStringFromFile()` で期待結果を構築するときは `\r\n` で固定の改行コードを使用しているのに対して、こちら（実際の値）は環境依存の改行コードが使われている気がします。
（Linux環境上で実行するとテストエラーになるかも？）

環境に依存しないようにそろえた方がいいかと思いました。

2021-11-24 10:18 UTC, kumagoro1202 commented on pom.xml
> +    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
そうですね。削除しました。
https://github.com/nablarch/nablarch-unpublished-api-checker/pull/1/commits/95d266501ffb98dde7de468446596aaf49095e00

2021-11-24 10:19 UTC, kumagoro1202 commented on src/test/java/nablarch/test/tool/findbugs/PublishedApisInfoTest.java
> +                        });
確かに読みやすいです。Comparator.comparing()のStreamは私も気にならないのでこのままいきます。
そのまま取り込みました。
https://github.com/nablarch/nablarch-unpublished-api-checker/pull/1/commits/efb404e4d456a7e29509c44da25d719162247f43

2021-11-24 10:20 UTC, kumagoro1202 commented on src/test/java/nablarch/test/tool/findbugs/PublishedApisInfoTest.java
> +            return sb.toString();
Files.readString()には行き着いてたんですが上の2つの方法は浮かびませんでした。
String.join()の案にしました。
https://github.com/nablarch/nablarch-unpublished-api-checker/pull/1/commits/71826b45d5adaec3af55819ba763da8c7de96d47

2021-11-24 10:20 UTC, kumagoro1202 commented on src/test/java/nablarch/test/tool/findbugs/PublishedApisInfoTest.java
> +                                    writer.newLine();
見落としていました。
修正しました。
https://github.com/nablarch/nablarch-unpublished-api-checker/pull/1/commits/efb404e4d456a7e29509c44da25d719162247f43#diff-e6e63a49ee72bef127b06ab21ec3f9f1e741a523f281dbd4e50d15f8982a8c2dR678

2021-11-25 05:08 UTC, opengl-8080 approved these changes

2021-11-25 05:08 UTC, merged